### ISSUE TITLE
Crash with Enchancement (1.21.1)

### ISSUE THREAD

**Issue by Lufurrius** [Chikorita-Lover/Kaleidoscope#3]
Crash on launch with [Enchancement](https://github.com/MoriyaShiine/enchancement)

Present mods: 
Mod Menu 11.0.3
Fabric API 0.110.0
Kaleidoscope 1.0.1
Enchancement r14

Crash Details:
```
java.lang.ExceptionInInitializerError
at knot//net.minecraft.class_2358.<clinit>(class_2358.java:43)
at knot//net.minecraft.class_2966.method_12851(class_2966.java:52)
at knot//net.minecraft.client.main.Main.main(Main.java:130)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2766 failed
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
at knot//net.minecraft.class_2741.<clinit>(class_2741.java:144)
... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
... 11 more
Caused by: java.lang.ExceptionInInitializerError
at knot//net.chikorita_lover.kaleidoscope.registry.KaleidoscopeSoundEvents.registerReference(KaleidoscopeSoundEvents.java:42)
at knot//net.chikorita_lover.kaleidoscope.registry.KaleidoscopeSoundEvents.registerReference(KaleidoscopeSoundEvents.java:38)
at knot//net.chikorita_lover.kaleidoscope.registry.KaleidoscopeSoundEvents.registerReference(KaleidoscopeSoundEvents.java:34)
at knot//net.chikorita_lover.kaleidoscope.registry.KaleidoscopeSoundEvents.<clinit>(KaleidoscopeSoundEvents.java:11)
at knot//net.chikorita_lover.kaleidoscope.KaleidoscopeEarlyRiser.lambda$run$0(KaleidoscopeEarlyRiser.java:20)
at knot//com.chocohead.mm.api.EnumAdder$EnumAddition.getParameters(EnumAdder.java:71)
at knot//com.chocohead.mm.EnumExtender.lambda$makeEnumExtender$0(EnumExtender.java:186)
at knot//com.chocohead.mm.Plugin.preApply(Plugin.java:378)
at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158)
at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1362)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1329)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:224)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
... 14 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5381 failed
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
at knot//net.minecraft.class_3414.<clinit>(class_3414.java:22)

```

**Comment by Chikorita-Lover** [comment]
Thanks for the report! This actually relates to another crash someone reported that I will look into getting patched soon.
